---
title: "How are the Jewish doing?"
description: |
  Let's dwelve into our first blog
author:
  - name: Hanh Ngo
    url: https://example.com/norajones
    affiliation: Spacely SprocketsB
    affiliation_url: https://example.com/spacelysprokets
date: 09-01-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
```

# Data description, including citing the data sources

```{r data-load}
data <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
raw_israel <- data %>%
  filter(countriesAndTerritories == "Israel") 
```

```{r raw-data}
raw_dat <- raw_israel %>%
  select(dateRep, day, month, year, cases, deaths, popData2019) %>%
  arrange(year, month, day) %>%
  mutate(cumulative_case = cumsum(cases))
```


# How i collect data?
This is interesting since i dont understand Hebrew




## Reference
https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

https://latitudelongitude.org/il/

https://www.geodatos.net/en/coordinates/israel
https://latitude.to/articles-by-country/il/israel/69512/kiryat-motzkin

http://www.longitude-latitude-maps.com/city/102_153,Pardes+Hanna-Karkur,Haifa,Israel

https://www.latlong.net/place/rehovot-israel-925.html